package com.example.electricityproject.shopp.userinfo.infodb;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.electricityproject.shopp.userinfo.infodb.UserInfoTable;

import com.example.electricityproject.shopp.userinfo.infodb.UserInfoTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoTableDaoConfig;

    private final UserInfoTableDao userInfoTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoTableDaoConfig = daoConfigMap.get(UserInfoTableDao.class).clone();
        userInfoTableDaoConfig.initIdentityScope(type);

        userInfoTableDao = new UserInfoTableDao(userInfoTableDaoConfig, this);

        registerDao(UserInfoTable.class, userInfoTableDao);
    }
    
    public void clear() {
        userInfoTableDaoConfig.clearIdentityScope();
    }

    public UserInfoTableDao getUserInfoTableDao() {
        return userInfoTableDao;
    }

}
