package com.example.framework.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.framework.db.DbTable;

import com.example.framework.db.DbTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbTableDaoConfig;

    private final DbTableDao dbTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbTableDaoConfig = daoConfigMap.get(DbTableDao.class).clone();
        dbTableDaoConfig.initIdentityScope(type);

        dbTableDao = new DbTableDao(dbTableDaoConfig, this);

        registerDao(DbTable.class, dbTableDao);
    }
    
    public void clear() {
        dbTableDaoConfig.clearIdentityScope();
    }

    public DbTableDao getDbTableDao() {
        return dbTableDao;
    }

}
