package com.example.framework.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.framework.db.AddressTable;
import com.example.framework.db.MessageTable;

import com.example.framework.db.AddressTableDao;
import com.example.framework.db.MessageTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addressTableDaoConfig;
    private final DaoConfig messageTableDaoConfig;

    private final AddressTableDao addressTableDao;
    private final MessageTableDao messageTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addressTableDaoConfig = daoConfigMap.get(AddressTableDao.class).clone();
        addressTableDaoConfig.initIdentityScope(type);

        messageTableDaoConfig = daoConfigMap.get(MessageTableDao.class).clone();
        messageTableDaoConfig.initIdentityScope(type);

        addressTableDao = new AddressTableDao(addressTableDaoConfig, this);
        messageTableDao = new MessageTableDao(messageTableDaoConfig, this);

        registerDao(AddressTable.class, addressTableDao);
        registerDao(MessageTable.class, messageTableDao);
    }
    
    public void clear() {
        addressTableDaoConfig.clearIdentityScope();
        messageTableDaoConfig.clearIdentityScope();
    }

    public AddressTableDao getAddressTableDao() {
        return addressTableDao;
    }

    public MessageTableDao getMessageTableDao() {
        return messageTableDao;
    }

}
