package com.example.framework.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.framework.greendao.CacheAddress;
import com.example.framework.greendao.CacheMessage;

import com.example.framework.greendao.CacheAddressDao;
import com.example.framework.greendao.CacheMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheAddressDaoConfig;
    private final DaoConfig cacheMessageDaoConfig;

    private final CacheAddressDao cacheAddressDao;
    private final CacheMessageDao cacheMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheAddressDaoConfig = daoConfigMap.get(CacheAddressDao.class).clone();
        cacheAddressDaoConfig.initIdentityScope(type);

        cacheMessageDaoConfig = daoConfigMap.get(CacheMessageDao.class).clone();
        cacheMessageDaoConfig.initIdentityScope(type);

        cacheAddressDao = new CacheAddressDao(cacheAddressDaoConfig, this);
        cacheMessageDao = new CacheMessageDao(cacheMessageDaoConfig, this);

        registerDao(CacheAddress.class, cacheAddressDao);
        registerDao(CacheMessage.class, cacheMessageDao);
    }
    
    public void clear() {
        cacheAddressDaoConfig.clearIdentityScope();
        cacheMessageDaoConfig.clearIdentityScope();
    }

    public CacheAddressDao getCacheAddressDao() {
        return cacheAddressDao;
    }

    public CacheMessageDao getCacheMessageDao() {
        return cacheMessageDao;
    }

}
