package com.fiannce.sql;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fiannce.sql.bean.MessageBean;
import com.fiannce.sql.bean.SqlBean;

import com.fiannce.sql.MessageBeanDao;
import com.fiannce.sql.SqlBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageBeanDaoConfig;
    private final DaoConfig sqlBeanDaoConfig;

    private final MessageBeanDao messageBeanDao;
    private final SqlBeanDao sqlBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageBeanDaoConfig = daoConfigMap.get(MessageBeanDao.class).clone();
        messageBeanDaoConfig.initIdentityScope(type);

        sqlBeanDaoConfig = daoConfigMap.get(SqlBeanDao.class).clone();
        sqlBeanDaoConfig.initIdentityScope(type);

        messageBeanDao = new MessageBeanDao(messageBeanDaoConfig, this);
        sqlBeanDao = new SqlBeanDao(sqlBeanDaoConfig, this);

        registerDao(MessageBean.class, messageBeanDao);
        registerDao(SqlBean.class, sqlBeanDao);
    }
    
    public void clear() {
        messageBeanDaoConfig.clearIdentityScope();
        sqlBeanDaoConfig.clearIdentityScope();
    }

    public MessageBeanDao getMessageBeanDao() {
        return messageBeanDao;
    }

    public SqlBeanDao getSqlBeanDao() {
        return sqlBeanDao;
    }

}
