package com.shoppingmall.detail.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shoppingmall.detail.greendao.GoodsTable;
import com.shoppingmall.detail.messagedao.MessageBean;

import com.shoppingmall.detail.dao.GoodsTableDao;
import com.shoppingmall.detail.dao.MessageBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsTableDaoConfig;
    private final DaoConfig messageBeanDaoConfig;

    private final GoodsTableDao goodsTableDao;
    private final MessageBeanDao messageBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsTableDaoConfig = daoConfigMap.get(GoodsTableDao.class).clone();
        goodsTableDaoConfig.initIdentityScope(type);

        messageBeanDaoConfig = daoConfigMap.get(MessageBeanDao.class).clone();
        messageBeanDaoConfig.initIdentityScope(type);

        goodsTableDao = new GoodsTableDao(goodsTableDaoConfig, this);
        messageBeanDao = new MessageBeanDao(messageBeanDaoConfig, this);

        registerDao(GoodsTable.class, goodsTableDao);
        registerDao(MessageBean.class, messageBeanDao);
    }
    
    public void clear() {
        goodsTableDaoConfig.clearIdentityScope();
        messageBeanDaoConfig.clearIdentityScope();
    }

    public GoodsTableDao getGoodsTableDao() {
        return goodsTableDao;
    }

    public MessageBeanDao getMessageBeanDao() {
        return messageBeanDao;
    }

}
