package com.example.common.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.common.db.MessageTable;

import com.example.common.db.MessageTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageTableDaoConfig;

    private final MessageTableDao messageTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageTableDaoConfig = daoConfigMap.get(MessageTableDao.class).clone();
        messageTableDaoConfig.initIdentityScope(type);

        messageTableDao = new MessageTableDao(messageTableDaoConfig, this);

        registerDao(MessageTable.class, messageTableDao);
    }
    
    public void clear() {
        messageTableDaoConfig.clearIdentityScope();
    }

    public MessageTableDao getMessageTableDao() {
        return messageTableDao;
    }

}
